name: sona_flutter
description: Sona is a cross-platform educational app which helps you remember facts easier, developed with Flutter.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  fluentui_system_icons: ^1.1.90
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  get_it: ^5.0.3
  moor: ^3.4.0
  path: ^1.7.0
  path_provider: ^1.6.27
  percent_indicator: ^2.1.9
  provider: ^4.3.2+3
  sqlite3_flutter_libs: ^0.3.0

dev_dependencies:
  build_runner: ^1.10.12
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  moor_generator: ^3.4.0
  pedantic: ^1.9.2

flutter:
  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Black.ttf
        - asset: assets/fonts/work_sans/WorkSans-BlackItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
        - asset: assets/fonts/work_sans/WorkSans-BoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraLight.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraLightItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Italic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Light.ttf
        - asset: assets/fonts/work_sans/WorkSans-LightItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
        - asset: assets/fonts/work_sans/WorkSans-MediumItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Thin.ttf
        - asset: assets/fonts/work_sans/WorkSans-ThinItalic.ttf
  uses-material-design: true
