name: sona_flutter
description: Sona is a cross-platform educational app which helps you remember facts easier, developed with Flutter.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
