name: sona_flutter
description: Sona is a cross-platform educational app which helps you remember facts easier, developed with Flutter.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  equatable: ^2.0.2
  fluentui_system_icons: ^1.1.126
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  get_it: ^7.1.3
  moor: ^4.3.2
  path: ^1.8.0
  path_provider: ^2.0.2
  percent_indicator: ^3.0.1
  provider: ^5.0.0
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.9
  moor_generator: ^4.3.1
  pedantic: ^1.11.0

flutter:
  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Black.ttf
        - asset: assets/fonts/work_sans/WorkSans-BlackItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
        - asset: assets/fonts/work_sans/WorkSans-BoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraLight.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraLightItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Italic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Light.ttf
        - asset: assets/fonts/work_sans/WorkSans-LightItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
        - asset: assets/fonts/work_sans/WorkSans-MediumItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Thin.ttf
        - asset: assets/fonts/work_sans/WorkSans-ThinItalic.ttf
  uses-material-design: true
