@startuml

skinparam wrapWidth 200
skinparam maxMessageSize 100
skinparam defaultFontName Monospaced
skinparam defaultFontSize 16
skinparam arrowFontSize 12
skinparam objectFontStyle bold
skinparam titleFontSize 24
skinparam titleFontStyle bold
skinparam shadowing false

header This diagram is part of a visualisation of the code written for Sona.\n View the project at github.com/cervonwong/sona-flutter.
title Dependencies between layers of the app.\n
footer Copyright (C) 2020 Cervon Wong

package Features <<Node>> {
	package Presentation <<Cloud>> {
		object "Widgets" as w
		object "State Management" as s {
			BLoC, ChangeNotifier...
		}
	}
	
	package Domain <<Cloud>> {
		object "Use Cases" as u
		object "Entities" as e
		object "Repo Interfaces" as ir
	}
	
	package Data <<Cloud>> {
		object "Repo Impls" as ri {
			and Entity<->Model mappers
		}
		object "DAO Impls" AS di {
			also Data Sources
		}
		object "DAO Interfaces" as id {
			also Data Sources
		}
		object "Moor Database" as db {
			Configs, Tables, Models
		}
	}

	note bottom of db
    	Models are part of the database due to the limitations of moor's builders. See <i>https://github.com/ simolus3/moor/issues/490</i>for progress on this :)
    end note
}

object "Service Locator" as sl {
	Injection Container for Dependency Injection
}

package Core <<Node>> {
	note "Constants, utils, shared components, etc." as n1
}

w  ....>  s
w  ....>  e
s  ....>  u
s  ....>  e
u  ....>  e
u  ....>  ir
ir ....>  e
ri ....|> ir
ri ....>  id
ri ....>  db
ri ....>  e
di ....>  db
di ....|> id
id ....> db

sl .> Features : \t
Features .> Core : \t

@enduml
