@startuml

skinparam defaultFontName Monospaced
skinparam defaultFontSize 16
skinparam objectFontStyle bold
skinparam titleFontSize 24
skinparam titleFontStyle bold
skinparam shadowing false

header This diagram is part of a visualisation of the code written for Sona.\n View the project at github.com/cervonwong/sona-flutter.
title Dependency relationships between main directories.\n
footer Copyright (C) 2020 Cervon Wong

object core {
	Shared components used throughout the app.
}

object screens {
	Widgets that represent a navigation destination. Screens depends on one or more feature packages.
}

object search {
	"filter/sort + table"
}
search <.. screens
core <.. search

object review {
	controls + presenter
}
review <.. screens
core <.. review

object scheduler {
	algorithm
}
scheduler <.. screens
core <.. scheduler

object editor {
	adding/updating entries
}
editor <.. screens
core <.. editor

object formatter {
	format style/structure
}
formatter <.. screens
core <.. formatter

object stats {
	graphs, etc.
}
stats <.. screens
core <.. stats

object deck {
	deck view, etc.
}
deck <.. screens
core <.. deck

@enduml
