name: Flutter Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  master:
    name: "Flutter Test"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@master
        with:
          channel: stable

      - run: flutter --version
      - run: dart --version
      - run: flutter pub get
      - run: flutter test
